bignerdranch/expandable-recycler-view

README.md
Added tag for Android-arsenal support.
@dgreenhalgh if you could merge this when you get a chance it should be really simple.
=> Added android-arsenal tag

expandablerecyclerview/src/main/AndroidManifest.xml
=> Remove application tag from library

app/src/main/java/com/ryanbrooks/expandablerecyclerviewsample/VerticalLinearRecyclerViewSample/CustomParentObject.java, criminalintentsample/src/main/java/com/bignerdranch/android/criminalintent/Crime.java, expandablerecyclerview/src/main/java/com/bignerdranch/expandablerecyclerview/Adapter/ExpandableRecyclerAdapter.java, expandablerecyclerview/src/main/java/com/bignerdranch/expandablerecyclerview/Model/ParentObject.java, expandablerecyclerview/src/main/java/com/bignerdranch/expandablerecyclerview/ViewHolder/ParentViewHolder.java
Some misc code cleanup:
- Constructors simplified
- Reduce logic for setting animation view and duration in binding method
- Removed unused methods/vars
- add annotations for IdRes args
=> Code Cleanup

expandablerecyclerview/src/main/java/com/bignerdranch/expandablerecyclerview/Adapter/ExpandableRecyclerAdapter.java
Allows access into the list that represents what is shown in the recycler view.
Fixes #64
=> relax visibility into helper items

app/src/main/java/com/ryanbrooks/expandablerecyclerviewsample/linear/horizontal/HorizontalLinearRecyclerViewSampleActivity.java, app/src/main/res/layout/activity_horizontal_linear_recycler_view_sample.xml, app/src/main/res/layout/list_item_parent_horizontal.xml, app/src/main/res/values/strings.xml, expandablerecyclerview/src/main/java/com/bignerdranch/expandablerecyclerview/Adapter/ExpandableRecyclerAdapter.java
Adds ability to add/remove parent objects into the adapter.
=> Parent object addition/removal

CHANGELOG.md, MIGRATION.md, README.md, gradle.properties
Cleaned up readme to account for changes made in 2.0.0.
=> Readme cleanup

CHANGELOG.md, expandablerecyclerview/src/main/java/com/bignerdranch/expandablerecyclerview/Adapter/ExpandableRecyclerAdapter.java, gradle.properties
=> notifyParentItemRangeInserted crash fix

README.md
Looks like we missed this in the last bug update.
=> Update readme to v2.0.1

README.md
Resolves #104.
To account for the adaptation of the `dev` branch model, I added some contribution instructions to the readme.
=> Added contribution instructions

CHANGELOG.md, README.md, app/src/main/java/com/ryanbrooks/expandablerecyclerviewsample/linear/horizontal/HorizontalLinearRecyclerViewSampleActivity.java, app/src/main/res/layout/activity_horizontal_linear_recycler_view_sample.xml, app/src/main/res/values/strings.xml, expandablerecyclerview/src/main/java/com/bignerdranch/expandablerecyclerview/Adapter/ExpandableRecyclerAdapter.java, gradle.properties
fixes #94 
We were not fetching the updated children objects which meant that new references were not being caught.
=> Fix notify(Parent/Child)ItemChanged methods

CHANGELOG.md, README.md, app/src/main/java/com/ryanbrooks/expandablerecyclerviewsample/linear/horizontal/HorizontalChild.java, app/src/main/java/com/ryanbrooks/expandablerecyclerviewsample/linear/horizontal/HorizontalParent.java, expandablerecyclerview/src/main/java/com/bignerdranch/expandablerecyclerview/Adapter/ExpandableRecyclerAdapter.java, gradle.properties
Fix crash when restoring state when an initially expanded row has been collapsed
fixes #122
=> Restore state crash

expandablerecyclerview/src/main/java/com/bignerdranch/expandablerecyclerview/Adapter/ExpandableRecyclerAdapter.java
Had a missing param and an errant `@{code}`
=> Javadoc fixes

criminalintentsample/build.gradle, expandablerecyclerview/build.gradle, sampleapp/build.gradle
Update support library version to 23.2.0
=> Update support library version to 23.2.0

.travis.yml, build.gradle, criminalintentsample/build.gradle, expandablerecyclerview/build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, sampleapp/build.gradle
=> Update Gradle and support lib

CONTRIBUTING, README.md
Added some information regarding breaking changes and version/branches to use.
=> Re-add contributing guidelines to readme

index.html
fixes #202, fixes #200 
Also removed the contributing bit as that is being re-added to the README, didn't seem to fit in this page.
=> Documentation fixes

.travis.yml, expandablerecyclerview/build.gradle, expandablerecyclerview/src/test/java/com/bignerdranch/expandablerecyclerview/model/ParentWrapperTest.java, scripts/build.sh
Welcome to the beginning of the effort to get this library under test. Started small with tests of the `ParentWrapper`.
=> Added ParentWrapperTest

.travis.yml, build.gradle, criminalintentsample/build.gradle, expandablerecyclerview/build.gradle, gradle/wrapper/gradle-wrapper.properties, sampleapp/build.gradle
From #254: Update to the SDK 24 and also corresponding libraries.
=> Update build tools and dependencies

expandablerecyclerview/src/main/java/com/bignerdranch/expandablerecyclerview/ExpandableRecyclerAdapter.java, expandablerecyclerview/src/test/java/com/bignerdranch/expandablerecyclerview/ExpandableRecyclerAdapterTest.java, expandablerecyclerview/src/test/java/com/bignerdranch/expandablerecyclerview/TestUtils.java
Testing the initialization reading the isInitiallyExpanded()
Testing collapseParent(), expandParent()
=> Initial ExpandableAdapter Tests

sampleapp/src/main/java/com/bignerdranch/expandablerecyclerviewsample/linear/vertical/RecipeAdapter.java
=> fix inflator/inflater typo

expandablerecyclerview/src/test/java/com/bignerdranch/expandablerecyclerview/ExpandableRecyclerAdapterTest.java
Tests for: notifyParentRangeInserted, notifyParentRangeRemoved, notifyParentChanged, notifyParentRangeChanged, notifyParentMoved
=> Rest of tests for parent notify methods

index.html
I corrected a couple of typos and out-of-date pieces of language on the website.
=> Corrected typos in website
